### ISSUE TITLE
Windows - Remember position of the hub

### ISSUE THREAD

**Issue by simonmarklar** [awaescher/RepoZ#110]
Hi,

Just started using this on windows and so far im loving it, but I have one thing thats cosmetic but would make me love this so much more. Super low priority as its really just my OCD... 

It would be amazing if I could position the hub where I want it and size it how i want it and when i reopen it,  the hub is where I last positioned it at the size i changed it to. Why? well, not everyone has the start bar across the bottom of the screen ;)

I used to be half decent at c# (many moons ago) so if you are open to it I can have a crack at it.

**Comment by awaescher** [comment]
> well, not everyone has the start bar across the bottom of the screen ;)

OMG, thanks for mentioning this. I am not a big fan of persisted screen bounds because you know, resolution or DPI scaling might change and things move and look weird or are moved off the screen. Even worse if screens are attached temporarily (like putting on a VR headset from time to time). And: I wanted RepoZ to be more like a "tray panel" and less like a form with Min/Max/Close buttons and a title bar (which you need to drag and size it).

So I'm not sure whether I want to do that or not but having a top taskbar and a bottom RepoZ really has to look wierd.

What do you think of having RepoZ opened at the top or the sides accordingly just like the network settings tray would pop up, for example?

**Comment by simonmarklar** [comment]
> What do you think of having RepoZ opened at the top or the sides accordingly just like the network settings tray would pop up, for example?

If RepoZ opened like the network settings then I would be so happy! thats exactly how I envisioned it

**Comment by awaescher** [comment]
[Version 5.4](https://github.com/awaescher/RepoZ/releases/tag/v5.4) was just released 🥳

**Comment by simonmarklar** [comment]
absolutely love it!!!!!!!!!!!!!
