### ISSUE TITLE
Is it possible to exclude git repos under "/" or "/home/XXX" when scanning ?

### ISSUE THREAD

**Issue by jiucenglou** [awaescher/RepoZ#120]
When scanning, RepoZ locates git repos under WSL. The "open in Windows file explorer" leads to the Windows path, which contains "AppData\Local\Packages\CanonicalGroupLimited.Ubuntu" and therefore it is unsafe to modify the repo. (It would be safe to modify through "\\wsl$" but the file system performance is unclear.) Could you suggest how to customize the root directory for scan or at least exclude git repos under WSL ? Many thanks !

**Comment by awaescher** [comment]
You can't set the root directory for scans manually. What you can do is ignoring the repositories per right-click, this will keep them from be tracked by RepoZ. However, there's **no** wildcard like "ignore everything under `C:\Users\Me\AppData\Local\*`"

**Comment by Shinkson47** [comment]
@awaescher I *beg* you to consider adding this as a feature.

With a local Time Machine backup of the entirety of my drives, RepoZ locates dozens, in some cases hundreds, of copies of the same repository. With each backup, this awesome utility is becoming more and more unusable.

Using the current solution I'm sure you can appreciate how impractical it is to manually remove around a thousand dupes, and keep on top of removing them every hour.

The ability to blacklist directories would more than suffice for my needs, but i could see adding regexes being a game changer to other users, too.

**Comment by awaescher** [comment]
Understood. Let me have a look at this.

**Comment by radaiko** [comment]
+1

**Comment by awaescher** [comment]
Ignoring repositories will be possible with wildcards in the next version. I chose a retricted set of wildcards over Regex because of performance considerations and because it does not require string escaping.

You can now edit the ignore file (`C:\Users\USERNAME\AppData\Roaming\RepoZ\Repositories.ignore`) manually, there's no UI for this at the moment.

Asterisk `*` wildcards are supported at the beginning and/or end of a path, like:
```
    C:\Users\USERNAME\AppData\Local*
    *AppData*
    *CanonicalGroupLimited.Ubuntu
```

You might want to ignore a repository in the UI and change the path(s) afterwards with wildcards.

I hope this fits your needs.
