### ISSUE TITLE
Explorer status duplicated and blinking

### ISSUE THREAD

**Issue by lecourtb** [awaescher/RepoZ#177]
Hello I got 2 repository states and one of them is blinking.
Here is the gif reproducing the issue:
![PbBlink](https://github.com/awaescher/RepoZ/assets/46935350/bcacd443-609e-4caa-82b7-b2edf56f80a9)
Not dramatic, but a little annoying !
Boris

**Comment by awaescher** [comment]
Nice. Which stats are correct `0 0` or `+3 ~0 -0`?

**Comment by lecourtb** [comment]
The blinking one is correct. 
I use RepoZ 5.5. 
Could it be due to a previous installation, not well cleaned ? 
Or is there another kind of tool that could be installed on my PC and provide similar function as RepoZ ?

**Comment by awaescher** [comment]
If I would know of another tool, I would not have written RepoZ I guess.
A previous installation surely not because it needs to be running to update the titles. Please make sure that there is only a single RepoZ.exe running in your task manager.
Could this be a repository with submodules maybe? So that RepoZ finds different repositories in that given path?
What happens for other repositories, like if you clone RepoZ locally?

**Comment by lecourtb** [comment]
One single RepoZ.exe is running

With process Explorer, I searched "RepoZ.exe":
![image](https://github.com/awaescher/RepoZ/assets/46935350/9fabae6b-3ab8-4a13-a212-3d6b6b83effe)
Probably more than expected ?

There is no submodules in my repo.

RepoZ repo locally:
![PbBlink2](https://github.com/awaescher/RepoZ/assets/46935350/837136c1-3621-431c-a91d-f842444ff6ff)

**Comment by lecourtb** [comment]
I understood !
[https://stackoverflow.com/questions/75950114/get-rid-of-extended-git-repository-information-shown-in-the-title-bar-of-explore](url)
Sorry, it was a feature I activated and forgot...
Thanks !
