### ISSUE TITLE
Improved display submodules

### ISSUE THREAD

**Issue by AlexTroshkin** [awaescher/RepoZ#39]
We have such projects as infrastructure (md-infrastructure\V2) and 'common code' (md-common\V2). They are connected in the form of submodules to other projects which are very many.

![47636-clip-155kb](https://user-images.githubusercontent.com/11016542/33209206-dbbb6758-d125-11e7-8835-ba8e4bc39b68.png)

Does not look good. It would be nice to hide this all in a collapsing list with submodules from each repository

**Comment by awaescher** [comment]
Submodules were not on my agenda, yet. Tagged as "enhancement", PRs welcome.

**Comment by evilrix** [comment]
Can I second this? We also make heavy use of submodules and, as a result, the RepoZ list is just full of the same few repeated submodules over and over. It makes, an otherwise good tool, pretty useless.

Related to this: rather than auto-search it would be nice to be able to just manually add repos. I have a huge number of repos on my dev machine, but I really don't want nor need them all in RepoZ. At the very least, there should be a way to remove those repos, from the list, that are not needed in there.

Thank you and I hope this feedback helps improve a really nice product.

**Comment by awaescher** [comment]
Good. Let's talk about that issue in detail. @AlexTroshkin, maybe you can help me out on that with your opinion as well.

Currently, I don't track the repos hierarchically. There's also no repository type the used library LibGit2Sharp tracks for me telling me whether or not a repository is a "parent" or sub repo.

This means, I should change RepoZ from a plain repository list to a hierarchical graph to get that feature working. I'm okay with that, however I predict a medium to high impact on performance on repository changes while doing so. As background: each and every file change in the repositories have to be recognized in RepoZ and matched to a tracked repository. There are quite a few tricks I came up with to get the impact of that to a minimum. I think you don't have a chance to know that these changes go through RepoZ even on a lower end machine and I'm a bit proud of this. Having a hierarchical graph of repositories forces me to do quite a lot comparisons on each file operation to find the matching repositories because some of the rules I can rely on today don't work anymore.

Given that we had that hierarchical graph: What would we do with the submodules other than hiding them or putting them into a collapsible menu structure we would not open very often? At least, that's what I think would happen.

In addition, I face another problem: I have a machine with multiple `s`-named repositories listed in RepoZ. These are working directories of a TFS build agent.  

So I came up with an alternative thought: I think we can simplify that all and as bonus resolve my `s` issue with repository ignores. What about adding a "Ignore by path" as git does it with files but for repositories? You could remove the sub-repositories you don't want to have in RepoZ and I could get rid of the `s`es.

And that's a perfect bridge to this:
> I have a huge number of repos on my dev machine, but I really don't want nor need them all in RepoZ. At the very least, there should be a way to remove those repos, from the list, that are not needed in there.

With ignorals, you could simply (and persistently) remove all the unwanted repositories now.

Pro tip: You don't have to scan your whole machine at all. If you start RepoZ the first time and it does not track any repository, it tells you to scan the machine or simply switch a branch in any repository to track it. That works, you can go ahead and type `git checkout master` (even if master is already is checked out) and RepoZ will immediate list it. 
If you want to clear the tracked repositories, simply delete the file `Repositories.cache` in `%APPDATA%\RepoZ`

So what would you say, @AlexTroshkin & @evilrix: Do you think that repository ignorals (with wildcards) would help you out? That means, without having a hierarchical structure?

**Comment by awaescher** [comment]
I took this as a "yes".
