### ISSUE TITLE
grrui on Windows should change drive

### ISSUE THREAD

**Issue by jeffrson** [awaescher/RepoZ#66]
When a repository is located on another drive than the current one, grrui should change the drive as well, not only the folder.

**Comment by awaescher** [comment]
grr and grrui build a command for the hosting console window to change the folder. This may lead that standing in `C:\`, the path to a repository will need to change the drive as well like `D:\Develop\RepoZ`, for example.

I suppose you run grr or grrui out of cmd.exe, because cmd.exe is not capable to change the drive by cd'ing to another folder implicitly. This has nothing to do with grr or grrui.

I suggest to use PowerShell instad as it is clever enough to change the drive when cd'ing into a new folder:

![Unbenannt](https://user-images.githubusercontent.com/3630638/55198325-e0906280-51b5-11e9-88b8-313bdb0200f7.png)

**Comment by elieux** [comment]
You mean there is a single command for all the shells? So even if there was a way to change drive in *cmd*, RepoZ can't use it?
