### ISSUE TITLE
Specify and/or exclude folders from scanning

### ISSUE THREAD

**Issue by jeffrson** [awaescher/RepoZ#67]
When RepoZ scans the computer for repositories it would help to specify where to search (drive or folder) or may be to exclude folders with known to be uninteresting repositories.

**Comment by awaescher** [comment]
Understood. However, I don't plan to implement that. Scanning for repositories is not required to work with RepoZ because it automatically detects repositories while you're working in there, for example if you checkout a git branch. Scanning for repositories is more like an optional "one time setup". That's why I don't see much improvement here.
