### ISSUE TITLE
Please use full text search for filtering repositories list

### ISSUE THREAD

**Issue by jeffrson** [awaescher/RepoZ#68]
Filtering the list of repositories apparently only searches for folder names.

However, there may be too many similar names. Let's say, I have subdirectories which represent the actual repositories or projects, and they contain folders with branches, like "develop". From searching "develop" I cannot tell which repository is the one I need.

If Repoz would search in branch names and folder names as well, the list could be reduced a lot more.

**Comment by awaescher** [comment]
I don't really get that. Would you please upload one or more screenshots?

Speaking for me, RepoZ is listing all repositories by the folder name, that's right. Because this is the closest thing I can think of to name a git repository. If I clone RepoZ from GitHub, the folder name is "RepoZ" as well by default. If I clone with an explicit name like `git clone https://github.com/awaescher/RepoZ RepoZ-The-Second`, "RepoZ-The-Second" is the folder name and therefore will be shown in RepoZ.

Okay, so the folder name is considered as repository name in RepoZ-jargon. The UI will then filter on the repository name, not its full repository path or any subdirectories.

<img width="344" alt="Screenshot 2019-03-28 at 12 19 10" src="https://user-images.githubusercontent.com/3630638/55153875-c9b92400-5153-11e9-8075-ba2b0ba54ba7.png">

**Comment by jeffrson** [comment]
Well, let's say I have repos "project1", "project2", "project3". Each project has it's folder.

In each folder there is a subfolder called "master", which contains the master branch. From master I add a worktree (git add worktree ../develop develop), such that each project folder contains another subfolder "develop".

As far as RepoZ is concerned, all those folders appear as "develop". I would like to filter for "project1", in order to see "master" and "develop" specifically for this project.

Furthermore, one might choose to name a branch with a rather long descriptive name, however use a shorter name for the worktree. E.g. there could be a branch "project1_webserve_config_ui" within a worktree called "ui". It would be nice to filter for "project1" or "webserve" regardless of the folder name.

**Comment by awaescher** [comment]
Okay. I've never seen a setup like this. I'm not even sure how you work with RepoZ then. 

However, the solution to filter for branches and paths was in my mind since a long time. You seem to be the first user which really needs that so I implemented it now.

RepoZ applied filters to the repository names in the past. That's still the default. However, you can now control that.

```
    "dev"      Filters on the name "dev"
    "n dev"    Filters on the name "dev", filter target "n " is optional
    "b dev"    Filters on the branch "dev"
    "p dev"    Filters on the path "dev"
```

These filter targets are available in RepoZ itself, grr and grrui once I merge branch `feature/Filter-Improvements`

![filters](https://user-images.githubusercontent.com/3630638/55362261-be5e5380-54d9-11e9-8199-159c6ca7313e.png)

**Comment by jeffrson** [comment]
Thanks!
