### ISSUE TITLE
[enhancement] RepoZ UI option to view each repo entry as a one-liner like grr.

### ISSUE THREAD

**Issue by intraz** [awaescher/RepoZ#91]
Could be very convenient when you have a long list of repos.

**Comment by awaescher** [comment]
Thanks for the idea, I though about that but I don't see any real benefit.
I think that the search box helps to get any list short. Doesn't it?

**Comment by intraz** [comment]
Where I work we have more than 30 repos (we work with microservices).
We regularly have work across several repos (sometimes on several branches).
The benefit of this feature would be seeing an overview of many repos at once with little or no scrolling.
This allows me to see the changes I made and whether or not I need to pull remote changes.

The search box only helps when you are looking for a specific repo or several repos with a shared part of their names.

Anyway, thank you for a cool and useful utility!

**Comment by awaescher** [comment]
Understood, thanks for the explanation. 

I think it would be better to group them anyways by a common property, otherwise you might have a *very* long list to overview mentally.

I have two ideas which might help ... both may fail:

1. If you're working on multiple repos and want to track the changes with little scrolling: I think the filter `todo` ([came with version 5.1](https://github.com/awaescher/RepoZ/releases)) might help. Anyway, it might show repositories with open changes you won't want to see in the list.
2. If you use similar branch name patterns (like with ticket numbers or any other common token) or the repositories are placed in relatable paths, you could use the filter targets "branch" or "path" like shown in the second picture below. Note the `b` or `p` prefix to filter on branch names or the repository path.

### TODO filter
![61980749-ebd68c00-aff7-11e9-899d-346299a81181](https://user-images.githubusercontent.com/3630638/72594875-d38d5d00-3908-11ea-9fa0-cde5497f2d82.png)

### Filter targets (branch or path)
![55436847-a0f2bd80-559d-11e9-8899-edac5f66855d](https://user-images.githubusercontent.com/3630638/72594994-1b13e900-3909-11ea-98e6-5e0296255e36.png)

**Comment by intraz** [comment]
Thanks a lot for the detailed reply.
I was not aware of these filters and will try them out.
I quickly tried 'todo' and it seems to fit my needs nicely.
I still like the one-liner repo info visual style but that's obviously just a personal preference.
Thanks again and keep up the good work!

**Comment by awaescher** [comment]
Okay, I‘ll look at it again due to personal sympathy. Let‘s reopen this.

**Comment by intraz** [comment]
Thanks a lot Andreas. Really appreciated.
Have a nice weekend.

**Comment by awaescher** [comment]
Dear intraz, I just went over the issues in my repositories and found this one. I'm sorry to say that but I don't see me doing this the next months so I'm closing this again.
I'm really not feeling well with this but keeping that issue open won't help anyone.

Pull requests are still welcome, of course.

**Comment by intraz** [comment]
Hi Andreas,
Not a problem.
Thank you for letting me know and for all the effort you put into RepoZ.
